AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for PokemonTypeMatchups Application
Globals:
  Function:
    Runtime: python3.9
    Timeout: 60
    Environment:
      Variables:
        ServiceName: !Ref ServiceName
        PipelineExecutionId: !Ref PipelineExecutionId
Parameters:
  ServiceName:
    Type: String
    Default: PokemonTypeMatchups
  PipelineExecutionId:
    Type: String
    Default: ""
Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"

  SecretsManagerSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "apps/${ServiceName}"
      Description: !Sub "Secret values for the ${ServiceName} application"
      SecretString: '{"alexaSkillId": ""}'

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Name: !Sub "${ServiceName}-ApiGateway"
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: "./api.yaml"
      MethodSettings:
      - LoggingLevel: ERROR
        ResourcePath: "/*"
        HttpMethod: "*"

  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: !Sub "${ServiceName}-Default-Usage-Plan"
      ApiStages:
        - ApiId: !Ref ApiGatewayApi
          Stage: !Ref ApiGatewayApi.Stage
      Description: !Sub "Default usage plan for the ${ServiceName} service"
      Quota:
        Limit: 5000
        Period: MONTH
      Throttle:
        BurstLimit: 200
        RateLimit: 100

  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: !Sub "${ServiceName}-Default-API-Key"
      Description: !Sub "Default API key for the ${ServiceName} service"
      Enabled: True
      StageKeys:
        - RestApiId: !Ref ApiGatewayApi
          StageName: !Ref ApiGatewayApi.Stage

  UsagePlanApiKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties: 
      KeyId: !Ref ApiKey
      KeyType: 'API_KEY'
      UsagePlanId: !Ref UsagePlan

  GetDefenseMatchupsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ServiceName}-GetDefenseMatchups"
      Role: !GetAtt LambdaRole.Arn
      CodeUri: app/
      Handler: api_handler.get_defensive_matchups
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGatewayApi
            Path: "/matchups/defense"
            Method: get
            Auth:
              ApiKeyRequired: true

  AlexaSkillsApiFunction:
    Type: AWS::Serverless::Function
    DependsOn: SecretsManagerSecret
    Properties:
      FunctionName: !Sub "${ServiceName}-AlexaSkillsApi"
      Role: !GetAtt LambdaRole.Arn
      CodeUri: app/
      Handler: alexa_skills_handler.handle_api_request
      Environment:
        Variables:
          AlexaSkillId: !Sub '{{resolve:secretsmanager:apps/${ServiceName}:SecretString:alexaSkillId}}'
      Events:
        Post:
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGatewayApi
            Path: "/alexa/skills"
            Method: post
            Auth:
              ApiKeyRequired: true

  AlexaSkillsFunction:
    Type: AWS::Serverless::Function
    DependsOn: SecretsManagerSecret
    Properties:
      FunctionName: !Sub "${ServiceName}-AlexaSkills"
      Role: !GetAtt LambdaRole.Arn
      CodeUri: app/
      Handler: alexa_skills_handler.handle_skill_request
      Environment:
        Variables:
          AlexaSkillId: !Sub '{{resolve:secretsmanager:apps/${ServiceName}:SecretString:alexaSkillId}}'
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill